import type { Metadata } from "next"; import PayCalculatorTASPage from "@/modules/state/pay-calculator-tas"; import { JsonLd } from "@/modules/seo/json-ld"; import type { BreadcrumbList, FAQPage, WebApplication, WithContext } from "schema-dts"; import { SITE_CONFIG } from "@/lib/constants";
import { ORGANIZATION_SCHEMA, calculatorHowTo, PAY_CALCULATOR_STEPS } from "@/lib/schema";
const BASE = SITE_CONFIG.baseUrl; const URL = `${BASE}/pay-calculator-tas/`;
export const metadata: Metadata = { title: "Pay Calculator Tasmania 2025-26 — TAS Take-Home Pay", description: "Calculate take-home pay in Tasmania. Federal tax rates, TAS payroll tax, Hobart average salaries. Free Tasmania pay calculator.", alternates: { canonical: URL }, openGraph: { title: "Pay Calculator TAS", description: "Calculate your net pay in Tasmania.", url: URL, siteName: SITE_CONFIG.name, type: "website", locale: "en_AU" } };
const breadcrumb: WithContext<BreadcrumbList> = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Pay Calculator", item: BASE }, { "@type": "ListItem", position: 2, name: "Pay Calculator TAS", item: URL }] };
const webAppSchema: WithContext<WebApplication> = { "@context": "https://schema.org", "@type": "WebApplication", name: "Pay Calculator Tasmania", url: URL, description: "Take-home pay calculator for Tasmania, Australia.", applicationCategory: "FinanceApplication", operatingSystem: "Web", browserRequirements: "Requires JavaScript", offers: { "@type": "Offer", price: "0", priceCurrency: "AUD" }, creator: { "@type": "Organization", name: SITE_CONFIG.name }, dateModified: new Date().toISOString().split("T")[0], inLanguage: "en-AU" };
const faq: WithContext<FAQPage> = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [{ "@type": "Question", name: "Is income tax different in Tasmania?", acceptedAnswer: { "@type": "Answer", text: "No. Income tax is set federally and is identical across all states." } }] };
const howToSchema = calculatorHowTo({ name: "How to Calculate Take-Home Pay in Tasmania", url: URL, description: "Calculate your take-home pay in Tasmania in under a minute.", steps: PAY_CALCULATOR_STEPS });
export default function Page() { return (<><JsonLd code={[breadcrumb, webAppSchema, faq, ORGANIZATION_SCHEMA, howToSchema]} /><PayCalculatorTASPage /></>); }
