import type { Metadata } from "next"; import PayCalculatorNTPage from "@/modules/state/pay-calculator-nt"; import { JsonLd } from "@/modules/seo/json-ld"; import type { BreadcrumbList, FAQPage, WebApplication, WithContext } from "schema-dts"; import { SITE_CONFIG } from "@/lib/constants";
import { ORGANIZATION_SCHEMA, calculatorHowTo, PAY_CALCULATOR_STEPS } from "@/lib/schema";
const BASE = SITE_CONFIG.baseUrl; const URL = `${BASE}/pay-calculator-nt/`;
export const metadata: Metadata = { title: "Pay Calculator NT — Northern Territory Take-Home Pay", description: "Calculate take-home pay in the NT. Zone tax offset eligibility, NT payroll tax, Darwin average salaries. Free Northern Territory pay calculator.", alternates: { canonical: URL }, openGraph: { title: "Pay Calculator NT", description: "Calculate your net pay in the Northern Territory.", url: URL, siteName: SITE_CONFIG.name, type: "website", locale: "en_AU" } };
const breadcrumb: WithContext<BreadcrumbList> = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Pay Calculator", item: BASE }, { "@type": "ListItem", position: 2, name: "Pay Calculator NT", item: URL }] };
const webAppSchema: WithContext<WebApplication> = { "@context": "https://schema.org", "@type": "WebApplication", name: "Pay Calculator NT", url: URL, description: "Take-home pay calculator for the Northern Territory, Australia.", applicationCategory: "FinanceApplication", operatingSystem: "Web", browserRequirements: "Requires JavaScript", offers: { "@type": "Offer", price: "0", priceCurrency: "AUD" }, creator: { "@type": "Organization", name: SITE_CONFIG.name }, dateModified: new Date().toISOString().split("T")[0], inLanguage: "en-AU" };
const faq: WithContext<FAQPage> = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [{ "@type": "Question", name: "Is income tax different in the NT?", acceptedAnswer: { "@type": "Answer", text: "No, but NT residents may qualify for the Zone Tax Offset." } }] };
const howToSchema = calculatorHowTo({ name: "How to Calculate Take-Home Pay in the Northern Territory", url: URL, description: "Calculate your take-home pay in the Northern Territory in under a minute.", steps: PAY_CALCULATOR_STEPS });
export default function Page() { return (<><JsonLd code={[breadcrumb, webAppSchema, faq, ORGANIZATION_SCHEMA, howToSchema]} /><PayCalculatorNTPage /></>); }
