import type { Metadata } from "next"; import PayCalculatorACTPage from "@/modules/state/pay-calculator-act"; import { JsonLd } from "@/modules/seo/json-ld"; import type { BreadcrumbList, FAQPage, WebApplication, WithContext } from "schema-dts"; import { SITE_CONFIG } from "@/lib/constants";
import { ORGANIZATION_SCHEMA, calculatorHowTo, PAY_CALCULATOR_STEPS } from "@/lib/schema";
const BASE = SITE_CONFIG.baseUrl; const URL = `${BASE}/pay-calculator-act/`;
export const metadata: Metadata = { title: "Pay Calculator ACT 2025-26 — Canberra Take-Home Pay", description: "Calculate take-home pay in the ACT. Federal tax rates, ACT payroll tax, Canberra average salaries. Free ACT pay calculator.", alternates: { canonical: URL }, openGraph: { title: "Pay Calculator ACT", description: "Calculate your net pay in Canberra.", url: URL, siteName: SITE_CONFIG.name, type: "website", locale: "en_AU" } };
const breadcrumb: WithContext<BreadcrumbList> = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Pay Calculator", item: BASE }, { "@type": "ListItem", position: 2, name: "Pay Calculator ACT", item: URL }] };
const webAppSchema: WithContext<WebApplication> = { "@context": "https://schema.org", "@type": "WebApplication", name: "Pay Calculator ACT", url: URL, description: "Take-home pay calculator for the ACT, Australia.", applicationCategory: "FinanceApplication", operatingSystem: "Web", browserRequirements: "Requires JavaScript", offers: { "@type": "Offer", price: "0", priceCurrency: "AUD" }, creator: { "@type": "Organization", name: SITE_CONFIG.name }, dateModified: new Date().toISOString().split("T")[0], inLanguage: "en-AU" };
const faq: WithContext<FAQPage> = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [{ "@type": "Question", name: "Is income tax different in the ACT?", acceptedAnswer: { "@type": "Answer", text: "No. Federal income tax rates apply uniformly across all states and territories." } }] };
const howToSchema = calculatorHowTo({ name: "How to Calculate Take-Home Pay in the ACT", url: URL, description: "Calculate your take-home pay in the ACT in under a minute.", steps: PAY_CALCULATOR_STEPS });
export default function Page() { return (<><JsonLd code={[breadcrumb, webAppSchema, faq, ORGANIZATION_SCHEMA, howToSchema]} /><PayCalculatorACTPage /></>); }
