import type { Metadata } from "next";
import FirstJobPayGuidePage from "@/modules/guide/first-job-pay-guide";
import { JsonLd } from "@/modules/seo/json-ld";
import type { BreadcrumbList, FAQPage, WebPage, WithContext } from "schema-dts";
import { SITE_CONFIG } from "@/lib/constants";
import { AUTHORS, GUIDE_AUTHORSHIP } from "@/lib/authors";
const BASE = SITE_CONFIG.baseUrl; const URL = `${BASE}/first-job-pay-guide/`;
export const metadata: Metadata = { title: "First Job Pay Guide — Tax, Super & Your First Payslip", description: "Starting your first job? Understand your pay from day one. Tax file number, superannuation, tax-free threshold, reading your first payslip, and how much you'll actually take home.", alternates: { canonical: URL }, openGraph: { title: "First Job Pay Guide Australia", description: "Tax, super & your first payslip explained for new Australian workers.", url: URL, siteName: SITE_CONFIG.name, type: "website", locale: "en_AU" }, twitter: { card: "summary_large_image", title: "First Job Pay Guide Australia", description: "Everything you need to know about your first pay." } };
const breadcrumb: WithContext<BreadcrumbList> = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Pay Calculator", item: BASE }, { "@type": "ListItem", position: 2, name: "First Job Pay Guide", item: URL }] };
const webPage: WithContext<WebPage> = { "@context": "https://schema.org", "@type": "WebPage", name: "First Job Pay Guide Australia", url: URL, publisher: { "@type": "Organization", name: SITE_CONFIG.name } };
const faq: WithContext<FAQPage> = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [{ "@type": "Question", name: "Why is my first pay less than expected?", acceptedAnswer: { "@type": "Answer", text: "Your employer deducts PAYG income tax from your gross pay before paying you. The amount deducted depends on your income level and whether you claimed the tax-free threshold." } }, { "@type": "Question", name: "Do I need a tax file number for my first job?", acceptedAnswer: { "@type": "Answer", text: "Yes. Without a TFN, your employer must withhold tax at the highest marginal rate of 45% plus Medicare levy. Apply for a TFN online through the ATO." } }] };
export default function Page() { return (<><JsonLd code={[breadcrumb, webPage, faq]} /><FirstJobPayGuidePage /></>); }
